accounts/urls.py
from django.urls import path, include

from accounts import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('account/<int:pk>/<str:status>', views.AccountView.as_view(), name='account'),
    path('account/favorites/<int:pk>', views.FavoritesView.as_view(), name='favorites'),
]

blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('', views.PostsView.as_view(), name='home'),

    path('post/add', views.AddPost.as_view(), name='add_post'),
    path('post/add/successfully', views.AddPostSuccessfully.as_view(), name='add_post_successfully'),
    path('post/<int:post_id>/comment/add', views.AddComment.as_view(), name='add_comment'),
    path('post/<int:pk>', views.PostView.as_view(), name='post_view'),
    path('post/<int:pk>/delete', views.DeletePost.as_view(), name='post_delete'),
    path('post/<int:pk>/to_favorites', views.PostToFavorites.as_view(), name='to_favorites'),
    path('post/<int:pk>/un_favorites', views.PostUnFavorites.as_view(), name='un_favorites'),

    path('posts', views.PostsView.as_view(), name='posts'),
    path('posts/topic/<str:topic_name>', views.PostsView.as_view(), name='topic_posts'),
    path('posts/tag/<str:tag_name>', views.PostsView.as_view(), name='tag_posts'),

    path('moderate/posts', views.ModeratorPostsView.as_view(), name='moderate_posts'),
    path('moderate/<int:post_id>/reject', views.PostReject.as_view(), name='post_reject'),
    path('moderate/<int:pk>', views.UpdatePost.as_view(), name='post_update'),
]

collectiveBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    class Meta(object):
        unique_together = ('email',)

    date_of_birth = models.DateField(null=True, blank=True)
    GENDERS = (
        ('m', 'male'),
        ('w', 'female'),
        ('o', 'other'),
    )
    gender = models.CharField(max_length=1, choices=GENDERS, default='o')

blog/models.py
from django.db import models

from accounts.models import User


# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    STATUS = (
        ('a', 'awaiting moderation'),
        ('r', 'rejected'),
        ('p', 'published'),
    )
    status = models.CharField(choices=STATUS, max_length=1, default='a')
    title = models.CharField(max_length=250)
    text = models.TextField()
    topics = models.ManyToManyField(Topic)
    tags = models.ManyToManyField(Tag)
    date_time_publication = models.DateTimeField(auto_now_add=True)
    number_views = models.IntegerField(default=0)

    def __str__(self):
        return "{} ({})".format(self.title, self.get_status_display())

    class Meta:
        permissions = (
            ('can_change_status', 'Can change post status'),
            ('can_see_non_published_posts', 'Can see non published posts'),
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date_time_publication = models.DateTimeField(auto_now=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text


class Favorite(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    posts = models.ManyToManyField(Post, blank=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='This field is required')

    class Meta:
        model = User
        fields = ('username', 'email', 'gender', 'date_of_birth', 'password1', 'password2',)
        help_texts = {
            'date_of_birth': "YYYY-MM-DD"
        }

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, FormView, ListView

from blog.models import Favorite
from . import services
from .forms import RegistrationForm
from .models import User


class RegistrationView(FormView):
    template_name = 'accounts/registration.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('posts')

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        services.create_favorite(user.id)
        return super().form_valid(form)


class AccountView(LoginRequiredMixin, DetailView):
    model = User

    def get_queryset(self):
        return services.get_user(self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(AccountView, self).get_context_data(**kwargs)
        context['posts'] = services.get_user_posts(user_id=self.kwargs['pk'], status=self.kwargs['status'])
        return context


class FavoritesView(LoginRequiredMixin, ListView):
    model = Favorite
    template_name = 'accounts/favorites.html'
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.id == self.kwargs['pk']:
            return services.get_favorites(self.kwargs['pk'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FavoritesView, self).get_context_data(**kwargs)
        context['user_id'] = self.request.user.id
        return context

accounts/templates/accounts/favorites.html
{% extends 'blog_basic.html' %}

{% block form %}
    {% if request.user.id == user_id %}
        <h2 class="text-center">Your favorite</h2>
        {% include 'blog/includes/posts.html' %}
    {% endif %}
{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'registration/registrarion_basic.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Registration
{% endblock %}

{% block form %}
    <div class="card shadow-lg">
        <div class="card-body">
            <h4 class="card-title text-center ">Registration</h4>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {{ form|crispy }}
                <button type="submit" class="btn btn-info btn-block ">Register now</button>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends 'blog_basic.html' %}

{% block form %}
    <div class="card shadow-lg">
        <h2 class="card-title text-center mt-1">
            {% if request.user.id == object.id %}
                Your page
            {% else %}
                {{ object.username|capfirst }} page
            {% endif %}
        </h2>
        <div class="card-body">
            <div class="card shadow-lg">
                <h4 class="card-title text-center mt-1">{{ object.username|capfirst }}</h4>
                <div class="card-body">
                    <p><strong>{{ object.first_name }} {{ object.last_name }}</strong>
                        <a class="float-right">
                            <strong> Last login:</strong> {{ object.last_login }}
                        </a>
                    </p>
                    <p><strong> Username:</strong> {{ object.username }} </p>
                    <p><strong> Email address:</strong> {{ object.email }}</p>
                    <p><strong> Date joined:</strong> {{ object.date_joined }}</p>
                    {% if  object.date_of_birth %}
                        <p><strong> Date of birth:</strong> {{ object.date_of_birth }}</p>
                    {% endif %}
                    {% if  object.gender %}
                        <p><strong> Gender:</strong> {{ object.get_gender_display|capfirst }}</p>
                    {% endif %}
                    {% if request.user.id == object.id %}
                        <a class="btn-sm btn-warning " href="{% url 'password_change' %}">Change password</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="card shadow-lg mt-5 mb-5">
        <h2 class="card-title text-center mt-1">
            {% if request.user.id != object.id %}
                {{ object.username|capfirst }} posts
            {% else %}
                Your posts
            {% endif %}
        </h2>
        <div class="card-body">
            {% if request.user.id == object.id %}
                <p>
                    <a class="btn btn-outline-success"
                       href="{% url 'account' pk=request.user.id status='p' %}">Published</a>
                    <a class="btn btn-outline-info" href="{% url 'account' pk=request.user.id status='a' %}">Pending
                        Moderation</a>
                    <a class="btn btn-outline-danger"
                       href="{% url 'account' pk=request.user.id status='r' %}">Rejected</a>
                </p>
            {% endif %}
            {% for post in posts %}
                {% if post.status == 'p' or request.user.id == object.id %}
                    <div class="card shadow-lg mt-3 ">
                        <div class="card-body">
                            <p class="ml-2">
                                <strong>{{ post.user|capfirst }}</strong> {{ post.date_time_publication }}
                            </p>
                            <div class="card-body">
                                <h4 class="card-title text-center mt-2">{{ post.title }}</h4>
                                <p class="">{{ post.text|truncatewords:8 }} </p>
                                <p class="ml-4 mr-3">
                                    {% if post.status == 'p' %}
                                        <p><strong>Number of comments:</strong> {{ post.comment_set.count }}</p>

                                        <a class="btn btn-info border-dark shadow"
                                           href="{% url 'post_view' pk=post.id %}">Read
                                            more</a>
                                        {% if request.user.id == post.user.id %}
                                            <a class="ml-2"
                                               href="{% url 'post_delete' pk=post.id %}">
                                                <svg width="1em" height="1em" viewBox="0 0 16 16"
                                                     class="bi bi-trash text-danger shadow"
                                                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                                    <path fill-rule="evenodd"
                                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                                </svg>
                                            </a>
                                        {% endif %}
                                        <a class="float-right mt-3">
                                            <svg width="1em" height="1em" viewBox="0 0 16 16"
                                                 class="bi bi-eye-fill ml-3"
                                                 fill="currentColor"
                                                 xmlns="http://www.w3.org/2000/svg">
                                                <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"></path>
                                                <path fill-rule="evenodd"
                                                      d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"></path>
                                            </svg>
                                            {{ post.number_views }}
                                        </a>
                                    {% elif post.status == 'a' %}
                                        <div class="alert-warning">
                                            <a>This article has not yet been moderated.</a>
                                        </div>
                                    {% elif post.status == 'r' %}
                                        <div class="alert-danger">
                                            <a>The article was rejected by a moderator.</a>
                                        </div>
                                    {% endif %}

                            </div>
                        </div>
                    </div>
                {% endif %}
            {% empty %}
                <h5 class="text-center mt-3">No posts yet</h5>
            {% endfor %}
        </div>
    </div>
{% endblock %}